"use strict";

try {
    //let x = 10;
    miFuncion();

} catch (error) {
    console.error(error);

} finally {
    //opcional
    console.log(`Termina la revisi√≥n de errores`)
}

console.log('continuamos...');